<?php
/**
 * Title: Reviews Widget
 * Slug: katomswold/reviews-widget
 * Categories: banner
 */
?>

<!-- wp:group {"metadata":{"categories":["banner"],"patternName":"katomswold/reviews-widget","name":"Reviews Widget"},"align":"full","style":{"spacing":{"padding":{"top":"0","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}},"backgroundColor":"colorfourteen","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-colorfourteen-background-color has-background" style="padding-top:0;padding-right:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--40)"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","align":"center","style":{"spacing":{"margin":{"bottom":"var:preset|spacing|40"}}}} -->
<figure class="wp-block-image aligncenter size-large" style="margin-bottom:var(--wp--preset--spacing--40)"><img src="" alt=""/></figure>
<!-- /wp:image -->

<!-- wp:heading {"textAlign":"center","align":"wide","style":{"typography":{"fontStyle":"normal","fontWeight":"300"},"spacing":{"margin":{"bottom":"var:preset|spacing|30"}}},"fontSize":"x-large"} -->
<h2 class="wp-block-heading alignwide has-text-align-center has-x-large-font-size" style="margin-bottom:var(--wp--preset--spacing--30);font-style:normal;font-weight:300">What people say</h2>
<!-- /wp:heading -->

<!-- wp:create-block/kateandtoms-reviews {"reviews":[{"review":"We have had the most wonderful week at Meadowbank. We loved the house, the stunning setting and exploring Chipping Campden and the Cotswolds  - it is all so beautiful","reviewer":"Amelia"},{"review":"Thank you for a wonderful week. The house was just right for our large family get together. It supported all our needs. We had such an amazing time and the weather added to the glory of the house, we were so glad it had a pool to cool off in the heat wave. We all kept remarking how it felt like we were in the South of France. My five year old boy, cried himself to sleep the night we got back, he wanted so desperately to go back and carry on the magic. We are looking at coming back to your company for a third time next year and have told all our friends, two of whom are considering making bookings.   May I also say what a great employee you have in Alison, she is such a lovely lady so welcoming and friendly.","reviewer":"Elizabeth"},{"review":"We had a fantastic weekend at Meadowbank House. It is in a beautiful position and is so well equipped and comfortable","reviewer":"Sue"},{"review":"Can I just say what an amazing weekend we had. The house was better than we could have hoped for, all the girls were so impressed with the house. You have been great and helped me no end to find the perfect place for my sister’s weekend. I will definitely recommend you to everyone I speak to, and no doubt will use your company again. Thanks","reviewer":"Amy"},{"review":"Just to say we had a really good time at the weekend, the house was great and despite the rain we managed to get in the pool and hot tub. We will be recommending your company to family and friends as the service we have received from you was great.","reviewer":"Michael"}],"textAlign":"center","reviewFontSize":"0.875rem","reviewerFontSize":"0.875rem","align":"wide"} -->
<div class="wp-block-create-block-kateandtoms-reviews alignwide has-text-align-center"><div class="reviews-container"><div class="review-item" data-index="0"><blockquote class="review-text" style="font-size:0.875rem">We have had the most wonderful week at Meadowbank. We loved the house, the stunning setting and exploring Chipping Campden and the Cotswolds  - it is all so beautiful</blockquote><cite class="reviewer-name" style="font-size:0.875rem">Amelia</cite></div><div class="review-item" data-index="1"><blockquote class="review-text" style="font-size:0.875rem">Thank you for a wonderful week. The house was just right for our large family get together. It supported all our needs. We had such an amazing time and the weather added to the glory of the house, we were so glad it had a pool to cool off in the heat wave. We all kept remarking how it felt like we were in the South of France. My five year old boy, cried himself to sleep the night we got back, he wanted so desperately to go back and carry on the magic. We are looking at coming back to your company for a third time next year and have told all our friends, two of whom are considering making bookings.   May I also say what a great employee you have in Alison, she is such a lovely lady so welcoming and friendly.</blockquote><cite class="reviewer-name" style="font-size:0.875rem">Elizabeth</cite></div><div class="review-item" data-index="2"><blockquote class="review-text" style="font-size:0.875rem">We had a fantastic weekend at Meadowbank House. It is in a beautiful position and is so well equipped and comfortable</blockquote><cite class="reviewer-name" style="font-size:0.875rem">Sue</cite></div><div class="review-item" data-index="3"><blockquote class="review-text" style="font-size:0.875rem">Can I just say what an amazing weekend we had. The house was better than we could have hoped for, all the girls were so impressed with the house. You have been great and helped me no end to find the perfect place for my sister’s weekend. I will definitely recommend you to everyone I speak to, and no doubt will use your company again. Thanks</blockquote><cite class="reviewer-name" style="font-size:0.875rem">Amy</cite></div><div class="review-item" data-index="4"><blockquote class="review-text" style="font-size:0.875rem">Just to say we had a really good time at the weekend, the house was great and despite the rain we managed to get in the pool and hot tub. We will be recommending your company to family and friends as the service we have received from you was great.</blockquote><cite class="reviewer-name" style="font-size:0.875rem">Michael</cite></div></div></div>
<!-- /wp:create-block/kateandtoms-reviews --></div>
<!-- /wp:group -->
